Update web resources from the main development branch
Squashed commit of the following:

commit c659addb3fc559770839685ef60fd1c74e235822
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:56:55 2019 +0700

    Provide migration initials and its respective config

commit c6dd7c4762f5ed747c14b24e9baa8480fec6d35c
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:54:26 2019 +0700

    Omit migrations in CircleCI config

commit 4b1eb62b345d950eaf7809fce42b7be85a92408f
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:51:15 2019 +0700

    Add a migration initialiser

commit 93d7e801a8efbfc3b6b93bcb725b87daaa334a5a
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:43:39 2019 +0700

    Minor addition of a migration step in CircleCI config

commit 4e2da833c806c422b682d7c871b1bb46dcb1836f
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:42:14 2019 +0700

    Minor CircleCI config

commit 760dc4599502521db936b6d4f6ec8a713df40d81
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:38:13 2019 +0700

    Reconfigure a CircleCI build step

commit dbd8c0b7a3670395832bfa2b6769f75ea47ecf6c
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:26:53 2019 +0700

    Revert the previous CircleCI config changes

commit 76a4026bcb41723fd2a1990486fa9384928113f1
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:20:16 2019 +0700

    Target migrations on the test database in CircleCI config

commit 6524aa06433fc06f54c481911d1ce0b905bf9571
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 23:11:44 2019 +0700

    Configure the default test database name

commit 8e280fbb4f26762f6a2af75332c428dfdb63d1c4
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 22:57:08 2019 +0700

    Purge migration scripts

commit a51411b5e3336b0687ff56a3d0e3f7c097d4bd29
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 17 22:48:13 2019 +0700

    Provide Django migration scripts for CircleCI builds

commit b296d07653fb7e88b1c840e19063449bd600d476
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Sun Nov 17 22:45:07 2019 +0700

    Addition of the recipe detail page (#16)

    * Provide the recipe base template

    * Provide a detail view

    * Provide the new breadcrumb nav and the recipe detail template

    * Bring in the recipe customisable unit feature

    * Provide the hyperlink to each recipe detail view

    * Enforce the sign-in guard on the user recipe list

    * Bring in the breadcrumb navigation and tags

    * Modify a content view

    * Provide sign-in routes for the auth guard

    * Register basic recipe properties into the detail view

    * Tests is total time correct

    * Remove irrelavant command scripts

    * Remove duplicated lines of Comment code

commit 37a2e8ac57935c636f091c2b4645f3a21d9f3734
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 16 00:27:05 2019 +0700

    Minor fixes in README.md

commit 4e4c5c91d5f58848ae736843efc7e8c7ca7cb2c5
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 16 00:18:36 2019 +0700

    Update more information in README.md

commit a3a1b762403143787f8441f31f167f642c660868
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Fri Nov 15 10:09:48 2019 +0700

    Refactor unit and quantity (#14)

    - Merge `ServingUnit` and `SpecialUnit`
    - rename `Units` to `units`
    - Add type hint to `units`
    - Remove depreciated and unused property `not_a_unit`
    - Add Quantity.__eq__ to support comparisons for tests
    - Prefer shorter symbol if any for `Quantity.get_db_str()`
    - Add QuantityField.deconstruct()
    - Remove kwargs['max_length']
    - Resolve changes with branch `task/command-loadrecipe`
    - Add Fraction
    - Add new units
    - Change from using float to Fraction in Quantity
    - Change type hint to allow amount in Quantity.__init__ to be int or float

commit fd98d30d0c244f2772c7fc721e29f3ae3119c0f4
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Fri Nov 15 10:03:29 2019 +0700

    Add sections + links according to instructions

commit f99ac260f969309166fad6890b68bc70964c4480
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Mon Nov 11 10:14:13 2019 +0700

    Update README.md: Add notes about branches

commit 202b5dc7ca7e72d0b78245f45be3e91d30040b50
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Mon Nov 11 09:19:31 2019 +0700

    Move save_cache up to only save requirements and not migrations

commit 10b45becece22e21c6d1151c8d1e8c304010575a
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 10 02:19:02 2019 +0700

    Add Content-Type header in the client-side fetch request

    (in the post stream template)

commit 887d82d13a4a983f96dcbf6e80f4b3992c136ac6
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 9 23:36:56 2019 +0700

    Deprecate the use of Docker image in triggering the deployment

commit b52f30748fea09829718517fa5cf574e88fea7f7
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 9 23:26:09 2019 +0700

    Allow the Docker image to have Django migrations itself

commit f14039fa24225d73b203cebd9b57e82a4911e592
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Sat Nov 9 23:18:00 2019 +0700

    Post stream feature integration (#8)

    * Split up routes and tests into separate folders

    * Start the controller folder with PostController

    * Provide the post creation form

    * Provide serialisable models for RESTful CRUD APIs

    * Alter the controller to conform with client-side requests

    * Add CRUD operation templates to the feature

    * Provide CRUD views and routes for the feature

    * Prettify the client-side code and templates

    * Minor fixes on the comment WIP text processor

    * Remove `null=True` + Add default aggregate_rating

commit a3fc609db002208e2f198f518c220022f4e67d29
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Fri Nov 8 10:45:26 2019 +0700

    Provide the customisable unit for ingredient feature for KooCook app (#6)

    * Tweak some models to fit the implementation

    * Tweak model supporters to fit the implementation

    * Add the conversion factor script

    * Provide a view mixin for the feature

    * Modify templates for customisable units

    (Crudely done)

    * Provide supporting models for the feature

    * Update the editing view for the feature

    * Provide editing UI components for the feature

    * Fix the client-side script for being non-reactive

    * Update the client-side script to update unit types

    * Format the client-side code

    * Integrate RecipeViewMixin with the update view

    * Add an ingredient removal button for each ingredient and decimal fixes

    * Merge branch 'task/command-populate-data' into feature/customisable-unit

    * Resolve the database constraints

commit 7719b4cc4bc04549efba3e6e361977913bee391b
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Nov 6 10:47:48 2019 +0700

    Add database configuration to Dockerfile

commit 66c93c5b537b5aabe4ed26928fa977d012407879
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Nov 6 09:23:07 2019 +0700

    Another update on README.md

commit bdfcd47ad2eb3c254634d441bc2736e9c5721ede
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Nov 6 00:43:04 2019 +0700

    Update README.md

    Change mockup link to link to branch `dev/common`

commit 4423cdb8dcc7567ff1f19a58a2f8cc9e3863b2df
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Nov 6 00:40:17 2019 +0700

    Update README.md

    Add related links

commit 46f7066acdeda265f649bfbecf5588a1812dcd76
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Tue Nov 5 02:23:50 2019 +0700

    Integrate 'task/models' changes to the development branch (#5)

    * Externalise configuration

    * Reorder CircleCI build steps

    * Fix the step order of the CircleCI build job

    * Add Unipath dep in requirements.txt

    * Add some starting models

    * Rename model Author to RecipeAuthor

    * Change Recipe.author to use RecipeAuthor

    * Add model: Tag

    * Fix Recipe Author field

    * Rename NutritionInfo to Nutrition

    * Add Tag to Recipe

    * Fix the default language code

    from 'en-uk' (which doesn't exist) to 'en-gb'

    * Remove the dependency 'Unipath'

    * Fix bug, Change default db file location, Change to use pathlib

    - Fix bug: "AttributeError: 'str' object has no attribute 'child'"
    resulting from changing from `unipath` to `os`

    - Change from `os` to `pathlib` to get the benefits of `unipath` while
    not increasing the dependencies and not losing the support of STL

    - Move `db.sqlite3` file back to the default location

    * Revert to dev/common config.yml

    * Reorder commands

    * Remove typo in config.yml

    * Try only do job 'build' on branches master and dev/common

    * Revert "Try only do job 'build' on branches master and dev/common"

    This reverts commit 27e8c63941d18b4989ec1e05c46ae7a61d5a76e6.

    * Try adding separating jobs 'build' and 'test'

    * Revert "Try adding separating jobs 'build' and 'test'"

    This reverts commit ea3956723702e812b565f222ab16ab438482822d.

    * Filtering branches in CircleCI workflow instead

    * Try moving the filter to workflow level

    * Revert "Try moving the filter to workflow level"

    This reverts commit 654d8eb82db44d9f7bd90fd638e04272e6ae7fde.

    * Add filter to job 'build' in workflow 'deploy'

    * Fix typo in .circle/config.yml

    * Try ignoring build-test on 'master' and 'dev/common'

    * Add models and fields with stub methods

    * Reorder / Format imports

    * Add Unit enums

    * Correct model `KooCookUser`

    * Rename fields in some models for clarity

    * Correct field specification in model `Recipe`

    * Add proxy property in `Recipe` for consistency

    * Refactor + Add "programmatic access" to `Unit`s

    "Programmatic access" now supports both singular and plural forms of the
    unit, its symbol, and with or without degrees for temperature
    specifically. Cannot ignore case yet.

    * Add `QuantityField` + separate files

    * Fix bugs in `QuantityField`

    * Replace `CharField` for `quantity` with `QuantityField`

    * Change import name to avoid collision

    * Add support for non-unit quantities

    * Solve 'null has no effect on ManyToManyField'

    * Update `recipe_yield` (QuantityField) in recipe.py

    * Add `URLField` 'video' to 'Recipe'

    * Remove deprecieated classes

    * Add `__all__` to modules to remove junk

    * Add `default` to fields that needs it

    * Resolve changes with branch 'dev' ('task/models')

    Co-authored-by: T. Bunratta <tharathorn.bu@ku.th>