Integrate 'task/models' changes to the development branch (#5)
* Externalise configuration

* Reorder CircleCI build steps

* Fix the step order of the CircleCI build job

* Add Unipath dep in requirements.txt

* Add some starting models

* Rename model Author to RecipeAuthor

* Change Recipe.author to use RecipeAuthor

* Add model: Tag

* Fix Recipe Author field

* Rename NutritionInfo to Nutrition

* Add Tag to Recipe

* Fix the default language code

from 'en-uk' (which doesn't exist) to 'en-gb'

* Remove the dependency 'Unipath'

* Fix bug, Change default db file location, Change to use pathlib

- Fix bug: "AttributeError: 'str' object has no attribute 'child'"
resulting from changing from `unipath` to `os`

- Change from `os` to `pathlib` to get the benefits of `unipath` while
not increasing the dependencies and not losing the support of STL

- Move `db.sqlite3` file back to the default location

* Revert to dev/common config.yml

* Reorder commands

* Remove typo in config.yml

* Try only do job 'build' on branches master and dev/common

* Revert "Try only do job 'build' on branches master and dev/common"

This reverts commit 27e8c63941d18b4989ec1e05c46ae7a61d5a76e6.

* Try adding separating jobs 'build' and 'test'

* Revert "Try adding separating jobs 'build' and 'test'"

This reverts commit ea3956723702e812b565f222ab16ab438482822d.

* Filtering branches in CircleCI workflow instead

* Try moving the filter to workflow level

* Revert "Try moving the filter to workflow level"

This reverts commit 654d8eb82db44d9f7bd90fd638e04272e6ae7fde.

* Add filter to job 'build' in workflow 'deploy'

* Fix typo in .circle/config.yml

* Try ignoring build-test on 'master' and 'dev/common'

* Add models and fields with stub methods

* Reorder / Format imports

* Add Unit enums

* Correct model `KooCookUser`

* Rename fields in some models for clarity

* Correct field specification in model `Recipe`

* Add proxy property in `Recipe` for consistency

* Refactor + Add "programmatic access" to `Unit`s

"Programmatic access" now supports both singular and plural forms of the
unit, its symbol, and with or without degrees for temperature
specifically. Cannot ignore case yet.

* Add `QuantityField` + separate files

* Fix bugs in `QuantityField`

* Replace `CharField` for `quantity` with `QuantityField`

* Change import name to avoid collision

* Add support for non-unit quantities

* Solve 'null has no effect on ManyToManyField'

* Update `recipe_yield` (QuantityField) in recipe.py

* Add `URLField` 'video' to 'Recipe'

* Remove deprecieated classes

* Add `__all__` to modules to remove junk

* Add `default` to fields that needs it

* Resolve changes with branch 'dev' ('task/models')

Co-authored-by: T. Bunratta <tharathorn.bu@ku.th>