Update the 'search' branch with contents from 'dev' branch
Squashed commit of the following:

commit 10b45becece22e21c6d1151c8d1e8c304010575a
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 10 02:19:02 2019 +0700

    Add Content-Type header in the client-side fetch request

    (in the post stream template)

commit 887d82d13a4a983f96dcbf6e80f4b3992c136ac6
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 9 23:36:56 2019 +0700

    Deprecate the use of Docker image in triggering the deployment

commit b52f30748fea09829718517fa5cf574e88fea7f7
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 9 23:26:09 2019 +0700

    Allow the Docker image to have Django migrations itself

commit f14039fa24225d73b203cebd9b57e82a4911e592
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Sat Nov 9 23:18:00 2019 +0700

    Post stream feature integration (#8)

    * Split up routes and tests into separate folders

    * Start the controller folder with PostController

    * Provide the post creation form

    * Provide serialisable models for RESTful CRUD APIs

    * Alter the controller to conform with client-side requests

    * Add CRUD operation templates to the feature

    * Provide CRUD views and routes for the feature

    * Prettify the client-side code and templates

    * Minor fixes on the comment WIP text processor

    * Remove `null=True` + Add default aggregate_rating

commit a3fc609db002208e2f198f518c220022f4e67d29
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Fri Nov 8 10:45:26 2019 +0700

    Provide the customisable unit for ingredient feature for KooCook app (#6)

    * Tweak some models to fit the implementation

    * Tweak model supporters to fit the implementation

    * Add the conversion factor script

    * Provide a view mixin for the feature

    * Modify templates for customisable units

    (Crudely done)

    * Provide supporting models for the feature

    * Update the editing view for the feature

    * Provide editing UI components for the feature

    * Fix the client-side script for being non-reactive

    * Update the client-side script to update unit types

    * Format the client-side code

    * Integrate RecipeViewMixin with the update view

    * Add an ingredient removal button for each ingredient and decimal fixes

    * Merge branch 'task/command-populate-data' into feature/customisable-unit

    * Resolve the database constraints

commit 7719b4cc4bc04549efba3e6e361977913bee391b
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Nov 6 10:47:48 2019 +0700

    Add database configuration to Dockerfile

commit 66c93c5b537b5aabe4ed26928fa977d012407879
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Nov 6 09:23:07 2019 +0700

    Another update on README.md

commit bdfcd47ad2eb3c254634d441bc2736e9c5721ede
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Nov 6 00:43:04 2019 +0700

    Update README.md

    Change mockup link to link to branch `dev/common`

commit 4423cdb8dcc7567ff1f19a58a2f8cc9e3863b2df
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Nov 6 00:40:17 2019 +0700

    Update README.md

    Add related links

commit 46f7066acdeda265f649bfbecf5588a1812dcd76
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Tue Nov 5 02:23:50 2019 +0700

    Integrate 'task/models' changes to the development branch (#5)

    * Externalise configuration

    * Reorder CircleCI build steps

    * Fix the step order of the CircleCI build job

    * Add Unipath dep in requirements.txt

    * Add some starting models

    * Rename model Author to RecipeAuthor

    * Change Recipe.author to use RecipeAuthor

    * Add model: Tag

    * Fix Recipe Author field

    * Rename NutritionInfo to Nutrition

    * Add Tag to Recipe

    * Fix the default language code

    from 'en-uk' (which doesn't exist) to 'en-gb'

    * Remove the dependency 'Unipath'

    * Fix bug, Change default db file location, Change to use pathlib

    - Fix bug: "AttributeError: 'str' object has no attribute 'child'"
    resulting from changing from `unipath` to `os`

    - Change from `os` to `pathlib` to get the benefits of `unipath` while
    not increasing the dependencies and not losing the support of STL

    - Move `db.sqlite3` file back to the default location

    * Revert to dev/common config.yml

    * Reorder commands

    * Remove typo in config.yml

    * Try only do job 'build' on branches master and dev/common

    * Revert "Try only do job 'build' on branches master and dev/common"

    This reverts commit 27e8c63941d18b4989ec1e05c46ae7a61d5a76e6.

    * Try adding separating jobs 'build' and 'test'

    * Revert "Try adding separating jobs 'build' and 'test'"

    This reverts commit ea3956723702e812b565f222ab16ab438482822d.

    * Filtering branches in CircleCI workflow instead

    * Try moving the filter to workflow level

    * Revert "Try moving the filter to workflow level"

    This reverts commit 654d8eb82db44d9f7bd90fd638e04272e6ae7fde.

    * Add filter to job 'build' in workflow 'deploy'

    * Fix typo in .circle/config.yml

    * Try ignoring build-test on 'master' and 'dev/common'

    * Add models and fields with stub methods

    * Reorder / Format imports

    * Add Unit enums

    * Correct model `KooCookUser`

    * Rename fields in some models for clarity

    * Correct field specification in model `Recipe`

    * Add proxy property in `Recipe` for consistency

    * Refactor + Add "programmatic access" to `Unit`s

    "Programmatic access" now supports both singular and plural forms of the
    unit, its symbol, and with or without degrees for temperature
    specifically. Cannot ignore case yet.

    * Add `QuantityField` + separate files

    * Fix bugs in `QuantityField`

    * Replace `CharField` for `quantity` with `QuantityField`

    * Change import name to avoid collision

    * Add support for non-unit quantities

    * Solve 'null has no effect on ManyToManyField'

    * Update `recipe_yield` (QuantityField) in recipe.py

    * Add `URLField` 'video' to 'Recipe'

    * Remove deprecieated classes

    * Add `__all__` to modules to remove junk

    * Add `default` to fields that needs it

    * Resolve changes with branch 'dev' ('task/models')

    Co-authored-by: T. Bunratta <tharathorn.bu@ku.th>

commit 5d00924251a245a4996627156656fb6766e85154
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Mon Nov 4 18:05:29 2019 +0700

    Squash merge with the branch 'task/models' (#4)

commit b0eff3421ffc4bfeb8e3e332064a5dd4a9ee8751
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Nov 4 11:46:05 2019 +0700

    Provide the Django database migrations again

commit adec967eca5c280d0f1307bf1346a7b9a4dcfaf9
Merge: 9f547eb be3cf16
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Nov 4 11:32:02 2019 +0700

    Merge branch 'feature/recipe-crud' into dev

    (To bring in the recipe CRUD features)

commit be3cf160de85cb184050436e50cf38550e1414be
Merge: 9e7e32f 9f547eb
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Nov 4 11:31:08 2019 +0700

    Resolve the static file directories conflict

commit 9f547ebe4ab927f3438fb6be6f1978100c7eaea8
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 19:28:56 2019 +0700

    Tidy up README.md and the unused config

commit 433c848c998917bca649a384a6f68849ca684ffc
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 19:11:50 2019 +0700

    Rename 'dev/common' branch in the CircleCI config

commit 9e7e32fb3ae613ec029024ab0f22bc06e0d19ebe
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 14:31:22 2019 +0700

    Update Recipe model and its relations

commit 15c7c8a184fd270a4ab0756085a180202fb20278
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 14:27:45 2019 +0700

    Enable all fields to be updated in a recipe edit view

commit 5f71e4ccbcb9d41944d19af5232a53c6821cd2a3
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 14:07:49 2019 +0700

    Rename all occurrences of RecipeAuthor

    (to just Author)

commit c902ea7a244d0be190b3bc5437bcfda693b33a98
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 14:03:45 2019 +0700

    Append image headers to user recipe cards

commit 6dbf310d1eb3d505351da972f024dc8b227d9fed
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 13:38:41 2019 +0700

    Separate columns of user recipes in half

commit d9e56296d2113d33d101359d5841bf12f8aca736
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 13:36:44 2019 +0700

    Update user recipe column sizes

commit 3d61596f47e7d63174d525f267ca428e65ba5468
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Nov 3 13:24:59 2019 +0700

    Apply Bulma standard style to a recipe edit view

commit e5c228fa86d88ab4eae7f64e1a5b3be0647dc188
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 23:28:53 2019 +0700

    Provide a preliminary recipe editing view

    (Quite messy)

commit 739f37d01ed6dde5d79171747774e20469f214f8
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 23:02:54 2019 +0700

    Provide a fully functional deletion modal

commit 71ce03416886468bbe510823184df73519d7b99e
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 03:39:40 2019 +0700

    Create a user recipe view and delete a recipe endpoint

commit b72ad807ae8cdd7d8d11a7bb65c1ba49b0b0dc20
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 02:25:18 2019 +0700

    Implement association of new recipes with KooCook users

commit 0551ccd0197f1c75ff30f5f42c144cbaa8e29dd7
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 02:21:57 2019 +0700

    Construct a recipe creation form

commit cdcdbad1cd4e0130739ae29db3a4013a9e5763c4
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Nov 2 00:01:57 2019 +0700

    Create a preliminary recipe creation page

commit bd69552ee87a182473cbbeb417ab97527ab8d032
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Fri Nov 1 12:48:46 2019 +0700

    Serve static files explicitly (remove later for prod!)

commit 9c546fcc973a897d8d97faa61e68daac4400c656
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Fri Nov 1 11:12:27 2019 +0700

    Move static files + Add path to `settings.py`

commit 016fba05c28d7c82a877e428adc8e3ef42ad9ebf
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Fri Nov 1 00:53:24 2019 +0700

    Add the build arg 'DEBUG' to Dockerfile

commit 080d9090e0312c24f023a2fccac84ccf11e8c9ba
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Thu Oct 31 23:52:35 2019 +0700

    Configure CircleCI to automate the deployment process

commit 1f574e1a1a1bb4e31f3d1f79a062eae209f9a648
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Thu Oct 31 21:06:36 2019 +0700

    Change the login redirect URL

commit 638b16bb52b43acf97905a01e701b9be5b733de5
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Thu Oct 31 16:50:14 2019 +0700

    Move templates directory to the right location

commit 2fd30c7a6fc5235892b756fc60a51b13adfbac29
Merge: 7b50b1f 9cd7fa0
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Thu Oct 31 13:00:49 2019 +0700

    Merge branch 'dev/frontend' into dev/common

commit 7b50b1f2f0b99052bf55a4221287ab312033662b
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Oct 30 17:32:44 2019 +0700

    Add arguments to the Dockerfile

commit ae98b5df4e8fccb0ad4dba34f6157ae63dfbd731
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Wed Oct 30 17:25:30 2019 +0700

    Add env vars to Dockerfile

commit 0f63da5848b141c40806faada0898e0a1119bde0
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Oct 30 16:56:35 2019 +0700

    Revert "Try changing workflow name to see if it helps"

    This reverts commit 9f1da2eaff584d737859c50f7fde427232c21cca.

commit 9f1da2eaff584d737859c50f7fde427232c21cca
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Wed Oct 30 16:53:54 2019 +0700

    Try changing workflow name to see if it helps

commit 1cafaa28398c4fd8fdfa0e3e0a04ef533e3697d0
Author: Tharathorn Bunrattanasathian <54201254+th-bunratta@users.noreply.github.com>
Date:   Wed Oct 30 16:47:24 2019 +0700

    Integrate changes from the dev/database branch into the common branch (#1)

    * Externalise configuration

    * Add some some models

    * Do CircleCI workflow 'build-test-deploy' only for 'master' and 'dev/common'

    * Try ignoring build-test on 'master' and 'dev/common'

commit 2af6448e2cddae0da61b082b9a91458bb174124b
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Oct 28 15:46:12 2019 +0700

    Fix CircleCI config

    (URL endpoint)

commit c7de27eefac33ea542fa41dd95a9d520a4d2fcee
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Oct 28 15:11:33 2019 +0700

    Fix CircleCI config on triggering the build job

commit c2708c8070816a8887a36ddca1fcc1be3d4ba15d
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Oct 28 14:28:44 2019 +0700

    Fix the CircleCI build API endpoint

commit 4d34515903382ed9c29bf3867bf56f6a4b1a71c0
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Oct 28 13:25:39 2019 +0700

    Alter CircleCI config to support the DEPLOY flag

commit f1d0b60b8c141891e8ee585ebc16a026711be759
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Mon Oct 28 12:53:09 2019 +0700

    Test out CircleCI config on triggering the build job

commit 6e9c6c8162e5e95b69dd23adff34043baba5b137
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Oct 27 21:42:39 2019 +0700

    Add the Django migration step

commit 8a28103b2f5dc52353a2e21bd40eb96968e391a4
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Oct 27 21:33:55 2019 +0700

    Patch Django allowed hosts

commit 3a37b38c6e925699c16a451af1ae957391deb3e0
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Oct 27 20:59:34 2019 +0700

    Append OpenSSH and Git to the installation step

commit 3e167931a1d17955eec5c85d8c6269a43d5c4783
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Oct 27 20:45:39 2019 +0700

    Remove gcloud from registering in Debian package registry

commit 6342fa628c03e90d98b870703037dd775c109222
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sun Oct 27 20:38:59 2019 +0700

    Remove GCP installation in Dockerfile

commit 9cd7fa076cccf3cefff898857cf6b577f1bedc17
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Sun Oct 27 18:01:14 2019 +0700

    Move templates to a shared folder

commit a710fd602301cd22aec446a0fdd842e7a56cc186
Author: Mai Mee <47658413+MaiMee1@users.noreply.github.com>
Date:   Sun Oct 27 18:00:27 2019 +0700

    Fix styling: add trailing comma and LF

commit 7efde2fe406636ac8b81d0f8926e3233863270ae
Author: plumest <chayathon.k@ku.th>
Date:   Sun Oct 27 17:28:22 2019 +0700

    Add Sample detail view

commit 040f60080c34f404b767b1fa2348856eb3ffb129
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 21:01:42 2019 +0700

    Allow CircleCi to copy the database file

    for deployment test

commit 550550cd6c6c2d189b0dae12bf77e9a1d372c2f0
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 20:44:45 2019 +0700

    Update requirements.txt for GAE deployment

commit f38a40324ac57b4fc07c6840d3f5733a9edfa7ff
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 20:23:39 2019 +0700

    Fix GAE configuration in CircleCI config file

commit c4f3ad47c0ebfe0eadac82d77e8ab2d357933b33
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 19:49:51 2019 +0700

    Fix CircleCI configuration file
    to copy the deployment config properly

commit 97644a5fa970e79985658fcfde607bfe7104271e
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 19:27:41 2019 +0700

    Configure CircleCI for deployment to GAE

commit d5e6e2b30c2f396d0f1f5b6adf1d8c61aa4cfd13
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 19:26:43 2019 +0700

    Reconfigure Dockerfile for deployment to GAE on GCP

commit 54f7edc877a2087373e2424e8ec2a5360a48b85e
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 17:37:53 2019 +0700

    Fix CircleCI configuration with Python local packages installed

commit cda37ee76fc223fba1486f183eb4facd45b55429
Author: T. Bunratta <tharathorn.bu@ku.th>
Date:   Sat Oct 26 17:34:07 2019 +0700

    Move dependency installation over to CircleCI