Fix bug, Change default db file location, Change to use pathlib
- Fix bug: "AttributeError: 'str' object has no attribute 'child'"
resulting from changing from `unipath` to `os`

- Change from `os` to `pathlib` to get the benefits of `unipath` while
not increasing the dependencies and not losing the support of STL

- Move `db.sqlite3` file back to the default location